const estados = [
  { value: "AC", label: "Acre" },
  { value: "AL", label: "Alagoas" },
  { value: "AP", label: "Amapá" },
  { value: "AM", label: "Amazonas" },
  { value: "BA", label: "Bahia" },
  { value: "CE", label: "Ceará" },
  { value: "DF", label: "Distrito Federal" },
  { value: "ES", label: "Espírito Santo" },
  { value: "GO", label: "Goiás" },
  { value: "MA", label: "Maranhão" },
  { value: "MT", label: "Mato Grosso" },
  { value: "MS", label: "Mato Grosso do Sul" },
  { value: "MG", label: "Minas Gerais" },
  { value: "PA", label: "Pará" },
  { value: "PB", label: "Paraíba" },
  { value: "PR", label: "Paraná" },
  { value: "PE", label: "Pernambuco" },
  { value: "PI", label: "Piauí" },
  { value: "RJ", label: "Rio de Janeiro" },
  { value: "RN", label: "Rio Grande do Norte" },
  { value: "RS", label: "Rio Grande do Sul" },
  { value: "RO", label: "Rondônia" },
  { value: "RR", label: "Roraima" },
  { value: "SC", label: "Santa Catarina" },
  { value: "SP", label: "São Paulo" },
  { value: "SE", label: "Sergipe" },
  { value: "TO", label: "Tocantins" },
];

const planetas = [
  { value: "Terra", label: "Terra" },
  { value: "Marte", label: "Marte" },
];

const paises = [
  { value: "Afeganistão", label: "AF" },
  { value: "África do Sul", label: "ZA" },
  { value: "Albânia", label: "AL" },
  { value: "Alemanha", label: "DE" },
  { value: "Andorra", label: "AD" },
  { value: "Angola", label: "AO" },
  { value: "Antígua e Barbuda", label: "AG" },
  { value: "Arábia Saudita", label: "SA" },
  { value: "Argélia", label: "DZ" },
  { value: "Argentina", label: "AR" },
  { value: "Armênia", label: "AM" },
  { value: "Austrália", label: "AU" },
  { value: "Áustria", label: "AT" },
  { value: "Azerbaijão", label: "AZ" },
  { value: "Bahamas", label: "BS" },
  { value: "Bangladesh", label: "BD" },
  { value: "Barbados", label: "BB" },
  { value: "Barém", label: "BH" },
  { value: "Belarus", label: "BY" },
  { value: "Bélgica", label: "BE" },
  { value: "Belize", label: "BZ" },
  { value: "Benin", label: "BJ" },
  { value: "Butão", label: "BT" },
  { value: "Bolívia", label: "BO" },
  { value: "Bósnia e Herzegovina", label: "BA" },
  { value: "Botswana", label: "BW" },
  { value: "Brasil", label: "BR" },
  { value: "Brunei", label: "BN" },
  { value: "Bulgária", label: "BG" },
  { value: "Burkina Faso", label: "BF" },
  { value: "Burundi", label: "BI" },
  { value: "Cabo Verde", label: "CV" },
  { value: "Camboja", label: "KH" },
  { value: "Camarões", label: "CM" },
  { value: "Canadá", label: "CA" },
  { value: "Catar", label: "QA" },
  { value: "Chade", label: "TD" },
  { value: "Chile", label: "CL" },
  { value: "China", label: "CN" },
  { value: "Chipre", label: "CY" },
  { value: "Colômbia", label: "CO" },
  { value: "Comores", label: "KM" },
  { value: "Congo (Brazzaville)", label: "CG" },
  { value: "Congo (Kinshasa)", label: "CD" },
  { value: "Coreia do Norte", label: "KP" },
  { value: "Coreia do Sul", label: "KR" },
  { value: "Costa do Marfim", label: "CI" },
  { value: "Costa Rica", label: "CR" },
  { value: "Croácia", label: "HR" },
  { value: "Cuba", label: "CU" },
  { value: "Dinamarca", label: "DK" },
  { value: "Djibouti", label: "DJ" },
  { value: "Dominica", label: "DM" },
  { value: "Egito", label: "EG" },
  { value: "El Salvador", label: "SV" },
  { value: "Emirados Árabes Unidos", label: "AE" },
  { value: "Equador", label: "EC" },
  { value: "Eritreia", label: "ER" },
  { value: "Eslováquia", label: "SK" },
  { value: "Eslovênia", label: "SI" },
  { value: "Espanha", label: "ES" },
  { value: "Estados Unidos", label: "US" },
  { value: "Estônia", label: "EE" },
  { value: "Etiópia", label: "ET" },
  { value: "Fiji", label: "FJ" },
  { value: "Filipinas", label: "PH" },
  { value: "Finlândia", label: "FI" },
  { value: "França", label: "FR" },
  { value: "Gabão", label: "GA" },
  { value: "Gâmbia", label: "GM" },
  { value: "Gana", label: "GH" },
  { value: "Geórgia", label: "GE" },
  { value: "Granada", label: "GD" },
  { value: "Grécia", label: "GR" },
  { value: "Guatemala", label: "GT" },
  { value: "Guiné", label: "GN" },
  { value: "Guiné-Bissau", label: "GW" },
  { value: "Guiné Equatorial", label: "GQ" },
  { value: "Guiana", label: "GY" },
  { value: "Haiti", label: "HT" },
  { value: "Honduras", label: "HN" },
  { value: "Hungria", label: "HU" },
  { value: "Iêmen", label: "YE" },
  { value: "Ilhas Marshall", label: "MH" },
  { value: "Ilhas Salomão", label: "SB" },
  { value: "Índia", label: "IN" },
  { value: "Indonésia", label: "ID" },
  { value: "Irã", label: "IR" },
  { value: "Iraque", label: "IQ" },
  { value: "Irlanda", label: "IE" },
  { value: "Islândia", label: "IS" },
  { value: "Israel", label: "IL" },
  { value: "Itália", label: "IT" },
  { value: "Jamaica", label: "JM" },
  { value: "Japão", label: "JP" },
  { value: "Jordânia", label: "JO" },
  { value: "Kazakhstan", label: "KZ" },
  { value: "Quênia", label: "KE" },
  { value: "Quirguistão", label: "KG" },
  { value: "Kiribati", label: "KI" },
  { value: "Kosovo", label: "XK" },
  { value: "Kuwait", label: "KW" },
  { value: "Laos", label: "LA" },
  { value: "Letônia", label: "LV" },
  { value: "Líbano", label: "LB" },
  { value: "Lesoto", label: "LS" },
  { value: "Libéria", label: "LR" },
  { value: "Líbia", label: "LY" },
  { value: "Liechtenstein", label: "LI" },
  { value: "Lituânia", label: "LT" },
  { value: "Luxemburgo", label: "LU" },
  { value: "Macedônia do Norte", label: "MK" },
  { value: "Madagascar", label: "MG" },
  { value: "Malásia", label: "MY" },
  { value: "Malawi", label: "MW" },
  { value: "Maldivas", label: "MV" },
  { value: "Mali", label: "ML" },
  { value: "Malta", label: "MT" },
  { value: "Marrocos", label: "MA" },
  { value: "Maurício", label: "MU" },
  { value: "Mauritânia", label: "MR" },
  { value: "México", label: "MX" },
  { value: "Micronésia", label: "FM" },
  { value: "Moçambique", label: "MZ" },
  { value: "Moldávia", label: "MD" },
  { value: "Mônaco", label: "MC" },
  { value: "Mongólia", label: "MN" },
  { value: "Montenegro", label: "ME" },
  { value: "Myanmar", label: "MM" },
  { value: "Namíbia", label: "NA" },
  { value: "Nauru", label: "NR" },
  { value: "Nepal", label: "NP" },
  { value: "Nicarágua", label: "NI" },
  { value: "Níger", label: "NE" },
  { value: "Nigéria", label: "NG" },
  { value: "Noruega", label: "NO" },
  { value: "Nova Zelândia", label: "NZ" },
  { value: "Omã", label: "OM" },
  { value: "Países Baixos", label: "NL" },
  { value: "Palau", label: "PW" },
  { value: "Panamá", label: "PA" },
  { value: "Papua-Nova Guiné", label: "PG" },
  { value: "Paquistão", label: "PK" },
  { value: "Paraguai", label: "PY" },
  { value: "Peru", label: "PE" },
  { value: "Polônia", label: "PL" },
  { value: "Portugal", label: "PT" },
  { value: "Reino Unido", label: "GB" },
  { value: "República Centro-Africana", label: "CF" },
  { value: "República Dominicana", label: "DO" },
  { value: "República Tcheca", label: "CZ" },
  { value: "Romênia", label: "RO" },
  { value: "Ruanda", label: "RW" },
  { value: "Rússia", label: "RU" },
  { value: "Samoa", label: "WS" },
  { value: "San Marino", label: "SM" },
  { value: "Santa Lúcia", label: "LC" },
  { value: "São Cristóvão e Nevis", label: "KN" },
  { value: "São Tomé e Príncipe", label: "ST" },
  { value: "São Vicente e Granadinas", label: "VC" },
  { value: "Senegal", label: "SN" },
  { value: "Sérvia", label: "RS" },
  { value: "Seychelles", label: "SC" },
  { value: "Serra Leoa", label: "SL" },
  { value: "Singapura", label: "SG" },
  { value: "Síria", label: "SY" },
  { value: "Somália", label: "SO" },
  { value: "Sri Lanka", label: "LK" },
  { value: "Suazilândia", label: "SZ" },
  { value: "Sudão", label: "SD" },
  { value: "Sudão do Sul", label: "SS" },
  { value: "Suécia", label: "SE" },
  { value: "Suíça", label: "CH" },
  { value: "Suriname", label: "SR" },
  { value: "Tailândia", label: "TH" },
  { value: "Tajiquistão", label: "TJ" },
  { value: "Tanzânia", label: "TZ" },
  { value: "Timor-Leste", label: "TL" },
  { value: "Togo", label: "TG" },
  { value: "Tonga", label: "TO" },
  { value: "Trinidad e Tobago", label: "TT" },
  { value: "Tunísia", label: "TN" },
  { value: "Turcomenistão", label: "TM" },
  { value: "Turquia", label: "TR" },
  { value: "Tuvalu", label: "TV" },
  { value: "Ucrânia", label: "UA" },
  { value: "Uganda", label: "UG" },
  { value: "Uruguai", label: "UY" },
  { value: "Uzbequistão", label: "UZ" },
  { value: "Vanuatu", label: "VU" },
  { value: "Vaticano", label: "VA" },
  { value: "Venezuela", label: "VE" },
  { value: "Vietnã", label: "VN" },
  { value: "Zâmbia", label: "ZM" },
  { value: "Zimbábue", label: "ZW" },
];

export { estados, planetas, paises };
